apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: ainfras-proxy
spec:
  selector:
    app: ainfras-proxy
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8080
  type: {{ .Values.service.type }}